Fixing ' syntax error, unexpected '}' '
fabianmichael/kirby-imageset pull request #26
Opened 2017-09-29 22:59 UTC by daybugging

2017-09-30 13:52 UTC, fabianmichael requested changes
Those paths are basically "virtual" paths provided by Kirby's router and are thus correct. The real path to the site folder is blocked by .htaccess. Please revert those examples.

Thanks for helping and pointing out the typo in my PHP example code!

See: https://getkirby.com/docs/developer-guide/plugins/assets

2017-10-01 22:55 UTC, daybugging reviewed
undid the path changes, merge ready.

2017-10-02 13:00 UTC, fabianmichael approved these changes

2017-10-02 13:00 UTC, merged

2017-10-02 13:01 UTC, fabianmichael commented
Thanks for your help! :-)